In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pyHIFU.transducer import Transducer, TElement
from pyHIFU.io.config import readjson
from pyHIFU.physics.medium import InitMedium
%matplotlib inline

config = readjson(json_path='../data/test_case1.json')

transducer_config = config['transducer']
coor_file_path = "../data/transducer_position.txt"
textarray = np.loadtxt(coor_file_path)
coordinates = textarray[::,1:]

In [2]:
init_medium_config = config['init_medium']
init_medium = InitMedium.new_markoil(init_medium_config['boundary'])

In [3]:
te = TElement(0, [0,0,0], 3.5e-3, 40, 1.2e6, np.array([0.14, 0,0]))
te.initialize(init_medium, 0, n=150, trident_angle=5e-2, theta_max=np.pi/20)

In [4]:
from pyHIFU.geometric import Vec3

In [7]:
n = 0
for tr in te:
    if Vec3.angle_between(tr.pow_ray.d, te.axial_ray.d) > np.pi/40:
        n += 1
print(n)

69


In [9]:
te.axial_ray.perpendicularDirection()

array([0., 1., 0.])

In [10]:
te.axial_ray.d

array([1., 0., 0.])

In [12]:
T = Transducer(element_coordinates=coordinates, **transducer_config)
T.initialize(init_medium, **transducer_config["element_init_paras"])

In [14]:
for te1 in T:
    print(np.dot(te.axial_ray.perpendicularDirection(), te.axial_ray.d))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [15]:
from pyHIFU.geometric import Vec3

In [24]:
v = Vec3.rotate(te.axial_ray.perpendicularDirection(), te.axial_ray.d, np.pi/10)
print(np.dot(v, te.axial_ray.d))

0.0


In [25]:
np.dot(v, te.axial_ray.perpendicularDirection())

0.9510565162951536

In [22]:
te.axial_ray.d

array([1., 0., 0.])

In [23]:
np.cos(np.pi/10)

0.9510565162951535

In [67]:
np.random.seed(1000)
np.random.random()

0.6535895854646095

In [42]:
import time

In [58]:
time.time()

1550228621.6568155

In [63]:
s = 0
for coo in coordinates:
    s += np.linalg.norm(coo - te.nature_f)
s / len(coordinates)

0.14000000294727155